// AUTO-GENERATED by scripts/generate-ha-registry.mjs — DO NOT EDIT BY HAND.
// Source: home-assistant/core generated discovery registries (Apache-2.0).
// Regenerate with: node scripts/generate-ha-registry.mjs

export type HaZeroconfRule = {
  brand: string;
  // Globs (fnmatch style: * and ?) matched case-insensitively.
  name?: string;
  properties?: Record<string, string>;
};

export type HaBluetoothRule = {
  brand: string;
  localName?: string;
  manufacturerId?: number;
  manufacturerDataStart?: number[];
  serviceUuid?: string;
  serviceDataUuid?: string;
};

// mDNS service type (e.g. "_airplay._tcp") → rules over the instance name and
// TXT-record properties.
export const HA_ZEROCONF: Record<string, HaZeroconfRule[]> = {
  "_PowerView-G3._tcp": [
    {
      "brand": "Hunter Douglas PowerView"
    }
  ],
  "_Volumio._tcp": [
    {
      "brand": "Volumio"
    }
  ],
  "_aicu-http._tcp": [
    {
      "brand": "ROMY Vacuum Cleaner"
    }
  ],
  "_airgradient._tcp": [
    {
      "brand": "AirGradient"
    }
  ],
  "_airplay._tcp": [
    {
      "brand": "Apple TV",
      "properties": {
        "model": "appletv*"
      }
    },
    {
      "brand": "Apple TV",
      "properties": {
        "model": "audioaccessory*"
      }
    },
    {
      "brand": "Apple TV",
      "properties": {
        "am": "airport*"
      }
    },
    {
      "brand": "Samsung Smart TV",
      "properties": {
        "manufacturer": "samsung*"
      }
    }
  ],
  "_airport._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_altruist._tcp": [
    {
      "brand": "Altruist"
    }
  ],
  "_amzn-alexa._tcp": [
    {
      "brand": "iRobot Roomba and Braava",
      "name": "irobot-*"
    },
    {
      "brand": "iRobot Roomba and Braava",
      "name": "roomba-*"
    }
  ],
  "_androidtvremote2._tcp": [
    {
      "brand": "Android TV Remote"
    }
  ],
  "_api._tcp": [
    {
      "brand": "Big Ass Fans",
      "properties": {
        "model": "haiku*"
      }
    },
    {
      "brand": "Big Ass Fans",
      "properties": {
        "model": "i6*"
      }
    }
  ],
  "_api._udp": [
    {
      "brand": "Elexa Guardian"
    }
  ],
  "_appletv-v2._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_axis-video._tcp": [
    {
      "brand": "Axis",
      "properties": {
        "macaddress": "00408c*"
      }
    },
    {
      "brand": "Axis",
      "properties": {
        "macaddress": "accc8e*"
      }
    },
    {
      "brand": "Axis",
      "properties": {
        "macaddress": "b8a44f*"
      }
    },
    {
      "brand": "Axis",
      "properties": {
        "macaddress": "e82725*"
      }
    },
    {
      "brand": "DoorBird",
      "properties": {
        "macaddress": "1ccae3*"
      }
    }
  ],
  "_bangolufsen._tcp": [
    {
      "brand": "Bang & Olufsen"
    }
  ],
  "_bbxsrv._tcp": [
    {
      "brand": "BleBox devices"
    }
  ],
  "_bond._tcp": [
    {
      "brand": "Bond"
    }
  ],
  "_companion-link._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_czc._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "czc*"
    }
  ],
  "_daap._tcp": [
    {
      "brand": "OwnTone"
    }
  ],
  "_deako._tcp": [
    {
      "brand": "Deako"
    }
  ],
  "_devialet-http._tcp": [
    {
      "brand": "Devialet"
    }
  ],
  "_dkapi._tcp": [
    {
      "brand": "Daikin AC"
    }
  ],
  "_droplet._tcp": [
    {
      "brand": "Droplet"
    }
  ],
  "_dvl-deviceapi._tcp": [
    {
      "brand": "devolo Home Control"
    },
    {
      "brand": "devolo Home Network",
      "properties": {
        "MT": "*"
      }
    }
  ],
  "_easylink._tcp": [
    {
      "brand": "Modern Forms",
      "name": "wac*"
    }
  ],
  "_ecobee._tcp": [
    {
      "brand": "ecobee"
    }
  ],
  "_elg._tcp": [
    {
      "brand": "Elgato Light"
    }
  ],
  "_elmax-ssl._tcp": [
    {
      "brand": "Elmax"
    }
  ],
  "_enphase-envoy._tcp": [
    {
      "brand": "Enphase Envoy"
    }
  ],
  "_esphomelib._tcp": [
    {
      "brand": "ESPHome"
    },
    {
      "brand": "Zigbee Home Automation",
      "name": "tube*"
    }
  ],
  "_fbx-api._tcp": [
    {
      "brand": "Freebox"
    }
  ],
  "_gasleser._tcp": [
    {
      "brand": "energieleser"
    }
  ],
  "_googlecast._tcp": [
    {
      "brand": "Google Cast"
    }
  ],
  "_hap._tcp": [
    {
      "brand": "HomeKit Device"
    },
    {
      "brand": "Z-Wave.Me",
      "name": "*z.wave-me*"
    }
  ],
  "_hap._udp": [
    {
      "brand": "HomeKit Device"
    }
  ],
  "_heos-audio._tcp": [
    {
      "brand": "Denon HEOS"
    }
  ],
  "_homeconnect._tcp": [
    {
      "brand": "Home Connect"
    }
  ],
  "_homekit._tcp": [
    {
      "brand": "HomeKit Bridge"
    }
  ],
  "_homewizard._tcp": [
    {
      "brand": "HomeWizard"
    }
  ],
  "_hscp._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_http._tcp": [
    {
      "brand": "air-Q",
      "properties": {
        "device": "air-q"
      }
    },
    {
      "brand": "Awair",
      "name": "awair*"
    },
    {
      "brand": "Bosch SHC",
      "name": "bosch shc*"
    },
    {
      "brand": "BSB-LAN",
      "name": "bsb-lan*"
    },
    {
      "brand": "Duco",
      "name": "duco [[][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][]].*"
    },
    {
      "brand": "EHEIM Digital",
      "name": "eheimdigital._http._tcp.local."
    },
    {
      "brand": "HDFury",
      "name": "diva-*"
    },
    {
      "brand": "HDFury",
      "name": "vertex2-*"
    },
    {
      "brand": "HDFury",
      "name": "vrroom-*"
    },
    {
      "brand": "Homevolt",
      "name": "homevolt*"
    },
    {
      "brand": "Indevolt",
      "name": "igen_fw*"
    },
    {
      "brand": "Lektrico Charging Station",
      "name": "lektrico*"
    },
    {
      "brand": "Liebherr",
      "name": "liebherr*"
    },
    {
      "brand": "LOQED Touch Smart Lock",
      "name": "loqed*"
    },
    {
      "brand": "Lunatone",
      "properties": {
        "manufacturer": "lunatone industrielle elektronik gmbh",
        "type": "dali-2-*",
        "uid": "*"
      }
    },
    {
      "brand": "Nettigo Air Monitor",
      "name": "nam-*"
    },
    {
      "brand": "Nettigo Air Monitor",
      "properties": {
        "manufacturer": "nettigo"
      }
    },
    {
      "brand": "Peblar",
      "name": "pblr-*"
    },
    {
      "brand": "Powerfox Cloud",
      "name": "powerfox*"
    },
    {
      "brand": "Powerfox Local",
      "name": "powerfox*"
    },
    {
      "brand": "Pure Energie",
      "name": "smartbridge*"
    },
    {
      "brand": "Rachio",
      "name": "rachio*"
    },
    {
      "brand": "RainMachine",
      "name": "rainmachine*"
    },
    {
      "brand": "Shelly",
      "name": "shelly*"
    },
    {
      "brand": "Slide Local",
      "name": "slide*"
    },
    {
      "brand": "Synology DSM",
      "properties": {
        "vendor": "synology*"
      }
    },
    {
      "brand": "Tailwind",
      "properties": {
        "vendor": "tailwind"
      }
    }
  ],
  "_hue._tcp": [
    {
      "brand": "Philips Hue"
    }
  ],
  "_hwenergy._tcp": [
    {
      "brand": "HomeWizard"
    }
  ],
  "_iometer._tcp": [
    {
      "brand": "IOmeter"
    }
  ],
  "_ipp._tcp": [
    {
      "brand": "Internet Printing Protocol (IPP)"
    }
  ],
  "_ipps._tcp": [
    {
      "brand": "Internet Printing Protocol (IPP)"
    }
  ],
  "_kiosker._tcp": [
    {
      "brand": "Kiosker"
    }
  ],
  "_kizbox._tcp": [
    {
      "brand": "Overkiz",
      "name": "gateway*"
    }
  ],
  "_kizboxdev._tcp": [
    {
      "brand": "Overkiz",
      "name": "gateway*"
    }
  ],
  "_linkplay._tcp": [
    {
      "brand": "LinkPlay"
    },
    {
      "brand": "WiiM"
    }
  ],
  "_lookin._tcp": [
    {
      "brand": "LOOKin"
    }
  ],
  "_lutron._tcp": [
    {
      "brand": "Lutron Caséta",
      "properties": {
        "SYSTYPE": "hwqs*"
      }
    },
    {
      "brand": "Lutron Caséta",
      "properties": {
        "SYSTYPE": "radiora3*"
      }
    },
    {
      "brand": "Lutron Caséta",
      "properties": {
        "SYSTYPE": "smartbridge*"
      }
    },
    {
      "brand": "Lutron Caséta",
      "properties": {
        "SYSTYPE": "ra2select*"
      }
    }
  ],
  "_mass._tcp": [
    {
      "brand": "Music Assistant"
    }
  ],
  "_matter._tcp": [
    {
      "brand": "Matter"
    }
  ],
  "_matterc._udp": [
    {
      "brand": "Matter"
    }
  ],
  "_mediaremotetv._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_meshcop._udp": [
    {
      "brand": "Thread"
    }
  ],
  "_mieleathome._tcp": [
    {
      "brand": "Miele"
    }
  ],
  "_miio._udp": [
    {
      "brand": "Xiaomi Gateway (Aqara)"
    },
    {
      "brand": "Xiaomi Home"
    },
    {
      "brand": "Yeelight",
      "name": "yeelink-*"
    }
  ],
  "_musc._tcp": [
    {
      "brand": "Bluesound"
    }
  ],
  "_nanoleafapi._tcp": [
    {
      "brand": "Nanoleaf"
    }
  ],
  "_nanoleafms._tcp": [
    {
      "brand": "Nanoleaf"
    }
  ],
  "_nrgkick._tcp": [
    {
      "brand": "NRGkick"
    }
  ],
  "_nut._tcp": [
    {
      "brand": "Network UPS Tools (NUT)"
    }
  ],
  "_octoprint._tcp": [
    {
      "brand": "OctoPrint"
    }
  ],
  "_openevse._tcp": [
    {
      "brand": "OpenEVSE"
    }
  ],
  "_owserver._tcp": [
    {
      "brand": "1-Wire"
    }
  ],
  "_philipstv_rpc._tcp": [
    {
      "brand": "Philips TV"
    }
  ],
  "_philipstv_s_rpc._tcp": [
    {
      "brand": "Philips TV"
    }
  ],
  "_plexmediasvr._tcp": [
    {
      "brand": "Plex Media Server"
    }
  ],
  "_plugwise._tcp": [
    {
      "brand": "Plugwise"
    }
  ],
  "_powerview._tcp": [
    {
      "brand": "Hunter Douglas PowerView"
    }
  ],
  "_prana._tcp": [
    {
      "brand": "Prana"
    }
  ],
  "_printer._tcp": [
    {
      "brand": "Brother Printer",
      "name": "brother*"
    }
  ],
  "_rabbitair._udp": [
    {
      "brand": "Rabbit Air"
    }
  ],
  "_raop._tcp": [
    {
      "brand": "Apple TV",
      "properties": {
        "am": "appletv*"
      }
    },
    {
      "brand": "Apple TV",
      "properties": {
        "am": "audioaccessory*"
      }
    },
    {
      "brand": "Apple TV",
      "properties": {
        "am": "airport*"
      }
    }
  ],
  "_rio._tcp": [
    {
      "brand": "Russound RIO"
    }
  ],
  "_shelly._tcp": [
    {
      "brand": "Shelly"
    }
  ],
  "_sideplay._tcp": [
    {
      "brand": "ecobee",
      "properties": {
        "mdl": "eb-*"
      }
    },
    {
      "brand": "ecobee",
      "properties": {
        "mdl": "ecobee*"
      }
    }
  ],
  "_sleep-proxy._udp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_slzb-06._tcp": [
    {
      "brand": "SMLIGHT SLZB"
    },
    {
      "brand": "Zigbee Home Automation",
      "name": "slzb-06*"
    }
  ],
  "_smoip._tcp": [
    {
      "brand": "Cambridge Audio"
    }
  ],
  "_solarman._tcp": [
    {
      "brand": "Solarman"
    }
  ],
  "_sonos._tcp": [
    {
      "brand": "Sonos"
    }
  ],
  "_soundtouch._tcp": [
    {
      "brand": "Bose SoundTouch"
    }
  ],
  "_ssh._tcp": [
    {
      "brand": "Homee",
      "name": "homee-*"
    },
    {
      "brand": "Smappee",
      "name": "smappee1*"
    },
    {
      "brand": "Smappee",
      "name": "smappee2*"
    },
    {
      "brand": "Smappee",
      "name": "smappee50*"
    }
  ],
  "_stream-magic._tcp": [
    {
      "brand": "Cambridge Audio"
    }
  ],
  "_stromleser._tcp": [
    {
      "brand": "energieleser"
    }
  ],
  "_system-bridge._tcp": [
    {
      "brand": "System Bridge"
    }
  ],
  "_systemnexa2._tcp": [
    {
      "brand": "System Nexa 2"
    }
  ],
  "_technove-stations._tcp": [
    {
      "brand": "TechnoVE"
    }
  ],
  "_touch-able._tcp": [
    {
      "brand": "Apple TV"
    }
  ],
  "_tvm._tcp": [
    {
      "brand": "Vogel's MotionMount"
    }
  ],
  "_uzg-01._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "uzg-01*"
    }
  ],
  "_vege._tcp": [
    {
      "brand": "Vegetronix VegeHub"
    }
  ],
  "_viziocast._tcp": [
    {
      "brand": "VIZIO SmartCast"
    }
  ],
  "_waermeleser._tcp": [
    {
      "brand": "energieleser"
    }
  ],
  "_wasserleser._tcp": [
    {
      "brand": "energieleser"
    }
  ],
  "_wattwaechter._tcp": [
    {
      "brand": "WattWächter Plus"
    }
  ],
  "_wled._tcp": [
    {
      "brand": "WLED"
    }
  ],
  "_wyoming._tcp": [
    {
      "brand": "Wyoming Protocol"
    }
  ],
  "_xbmc-jsonrpc-h._tcp": [
    {
      "brand": "Kodi"
    }
  ],
  "_xzg._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "xzg*"
    }
  ],
  "_zigate-zigbee-gateway._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "*zigate*"
    }
  ],
  "_zigbee-coordinator._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "*"
    }
  ],
  "_zigstar_gw._tcp": [
    {
      "brand": "Zigbee Home Automation",
      "name": "*zigstar*"
    }
  ],
  "_zwave-js-server._tcp": [
    {
      "brand": "Z-Wave"
    }
  ]
};

// Every key in `match` must match the corresponding SSDP field (globs allowed).
export const HA_SSDP: { brand: string; match: Record<string, string> }[] = [
  {
    "brand": "Arcam FMJ Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "ARCAM"
    }
  },
  {
    "brand": "Axis",
    "match": {
      "manufacturer": "AXIS"
    }
  },
  {
    "brand": "Sony Bravia TV",
    "match": {
      "manufacturer": "Sony Corporation",
      "st": "urn:schemas-sony-com:service:ScalarWebAPI:1"
    }
  },
  {
    "brand": "Control4",
    "match": {
      "st": "c4:director"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "Denon"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "DENON"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "DENON PROFESSIONAL"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "Marantz"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "manufacturer": "Denon"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "manufacturer": "DENON"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "manufacturer": "DENON PROFESSIONAL"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "manufacturer": "Marantz"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-denon-com:device:AiosDevice:1",
      "manufacturer": "Denon"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-denon-com:device:AiosDevice:1",
      "manufacturer": "DENON"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-denon-com:device:AiosDevice:1",
      "manufacturer": "DENON PROFESSIONAL"
    }
  },
  {
    "brand": "Denon AVR Network Receivers",
    "match": {
      "deviceType": "urn:schemas-denon-com:device:AiosDevice:1",
      "manufacturer": "Marantz"
    }
  },
  {
    "brand": "DirecTV",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "manufacturer": "DIRECTV"
    }
  },
  {
    "brand": "DLNA Digital Media Renderer",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "st": "urn:schemas-upnp-org:device:MediaRenderer:1"
    }
  },
  {
    "brand": "DLNA Digital Media Renderer",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:2",
      "st": "urn:schemas-upnp-org:device:MediaRenderer:2"
    }
  },
  {
    "brand": "DLNA Digital Media Renderer",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:3",
      "st": "urn:schemas-upnp-org:device:MediaRenderer:3"
    }
  },
  {
    "brand": "DLNA Digital Media Server",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:1",
      "st": "urn:schemas-upnp-org:device:MediaServer:1"
    }
  },
  {
    "brand": "DLNA Digital Media Server",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:2",
      "st": "urn:schemas-upnp-org:device:MediaServer:2"
    }
  },
  {
    "brand": "DLNA Digital Media Server",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:3",
      "st": "urn:schemas-upnp-org:device:MediaServer:3"
    }
  },
  {
    "brand": "DLNA Digital Media Server",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaServer:4",
      "st": "urn:schemas-upnp-org:device:MediaServer:4"
    }
  },
  {
    "brand": "FRITZ!Box Tools",
    "match": {
      "st": "urn:schemas-upnp-org:device:fritzbox:1"
    }
  },
  {
    "brand": "FRITZ!SmartHome",
    "match": {
      "st": "urn:schemas-upnp-org:device:fritzbox:1"
    }
  },
  {
    "brand": "Frontier Silicon",
    "match": {
      "st": "urn:schemas-frontier-silicon-com:undok:fsapi:1"
    }
  },
  {
    "brand": "Logitech Harmony Hub",
    "match": {
      "deviceType": "urn:myharmony-com:device:harmony:1",
      "manufacturer": "Logitech"
    }
  },
  {
    "brand": "Hegel Amplifier",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "Hegel"
    }
  },
  {
    "brand": "Denon HEOS",
    "match": {
      "st": "urn:schemas-denon-com:device:ACT-Denon:1"
    }
  },
  {
    "brand": "Huawei LTE",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "Huawei"
    }
  },
  {
    "brand": "Huawei LTE",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "Huawei Technologies Co., Ltd."
    }
  },
  {
    "brand": "Huawei LTE",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "SOYEA TECHNOLOGY CO., LTD."
    }
  },
  {
    "brand": "Hyperion",
    "match": {
      "manufacturer": "Hyperion Open Source Ambient Lighting",
      "st": "urn:hyperion-project.org:device:basic:1"
    }
  },
  {
    "brand": "Imeon Inverter",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:Basic:1",
      "manufacturer": "IMEON",
      "st": "upnp:rootdevice"
    }
  },
  {
    "brand": "Universal Devices ISY/IoX",
    "match": {
      "deviceType": "urn:udi-com:device:X_Insteon_Lighting_Device:1",
      "manufacturer": "Universal Devices Inc."
    }
  },
  {
    "brand": "Kaleidescape",
    "match": {
      "deviceType": "schemas-upnp-org:device:Basic:1",
      "manufacturer": "Kaleidescape, Inc."
    }
  },
  {
    "brand": "Keenetic NDMS2 Router",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "Keenetic Ltd."
    }
  },
  {
    "brand": "Keenetic NDMS2 Router",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "ZyXEL Communications Corp."
    }
  },
  {
    "brand": "LaMetric",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:LaMetric:1"
    }
  },
  {
    "brand": "Lyngdorf",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:2",
      "manufacturer": "Lyngdorf"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "Nanoleaf_aurora:light"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "nanoleaf:nl29"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "nanoleaf:nl42"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "nanoleaf:nl52"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "nanoleaf:nl69"
    }
  },
  {
    "brand": "Nanoleaf",
    "match": {
      "st": "inanoleaf:nl81"
    }
  },
  {
    "brand": "NETGEAR",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:InternetGatewayDevice:1",
      "manufacturer": "NETGEAR, Inc."
    }
  },
  {
    "brand": "OctoPrint",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:Basic:1",
      "manufacturer": "The OctoPrint Project"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "ONKYO"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:2",
      "manufacturer": "ONKYO"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:3",
      "manufacturer": "ONKYO"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "Onkyo & Pioneer Corporation"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:2",
      "manufacturer": "Onkyo & Pioneer Corporation"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:3",
      "manufacturer": "Onkyo & Pioneer Corporation"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:1",
      "manufacturer": "Pioneer"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:2",
      "manufacturer": "Pioneer"
    }
  },
  {
    "brand": "Onkyo",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:MediaRenderer:3",
      "manufacturer": "Pioneer"
    }
  },
  {
    "brand": "Linn / OpenHome",
    "match": {
      "st": "urn:av-openhome-org:service:Product:1"
    }
  },
  {
    "brand": "Linn / OpenHome",
    "match": {
      "st": "urn:av-openhome-org:service:Product:2"
    }
  },
  {
    "brand": "Linn / OpenHome",
    "match": {
      "st": "urn:av-openhome-org:service:Product:3"
    }
  },
  {
    "brand": "Linn / OpenHome",
    "match": {
      "st": "urn:av-openhome-org:service:Product:4"
    }
  },
  {
    "brand": "Roku",
    "match": {
      "deviceType": "urn:roku-com:device:player:1-0",
      "manufacturer": "Roku",
      "st": "roku:ecp"
    }
  },
  {
    "brand": "Samsung Smart TV",
    "match": {
      "st": "urn:samsung.com:device:RemoteControlReceiver:1"
    }
  },
  {
    "brand": "Samsung Smart TV",
    "match": {
      "st": "urn:samsung.com:service:MainTVAgent2:1"
    }
  },
  {
    "brand": "Samsung Smart TV",
    "match": {
      "manufacturer": "Samsung",
      "st": "urn:schemas-upnp-org:service:RenderingControl:1"
    }
  },
  {
    "brand": "Samsung Smart TV",
    "match": {
      "manufacturer": "Samsung Electronics",
      "st": "urn:schemas-upnp-org:service:RenderingControl:1"
    }
  },
  {
    "brand": "Sony Songpal",
    "match": {
      "manufacturer": "Sony Corporation",
      "st": "urn:schemas-sony-com:service:ScalarWebAPI:1"
    }
  },
  {
    "brand": "Sonos",
    "match": {
      "st": "urn:schemas-upnp-org:device:ZonePlayer:1"
    }
  },
  {
    "brand": "Samsung SyncThru Printer",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:Printer:1",
      "manufacturer": "Samsung Electronics"
    }
  },
  {
    "brand": "Synology DSM",
    "match": {
      "deviceType": "urn:schemas-upnp-org:device:Basic:1",
      "manufacturer": "Synology"
    }
  },
  {
    "brand": "UniFi Discovery",
    "match": {
      "manufacturer": "Ubiquiti Networks",
      "modelDescription": "UniFi Dream Machine"
    }
  },
  {
    "brand": "UniFi Discovery",
    "match": {
      "manufacturer": "Ubiquiti Networks",
      "modelDescription": "UniFi Dream Machine Pro"
    }
  },
  {
    "brand": "UniFi Discovery",
    "match": {
      "manufacturer": "Ubiquiti Networks",
      "modelDescription": "UniFi Dream Machine SE"
    }
  },
  {
    "brand": "UniFi Discovery",
    "match": {
      "manufacturer": "Ubiquiti Networks",
      "modelDescription": "UniFi Dream Machine Pro Max"
    }
  },
  {
    "brand": "UPnP/IGD",
    "match": {
      "st": "urn:schemas-upnp-org:device:InternetGatewayDevice:1"
    }
  },
  {
    "brand": "UPnP/IGD",
    "match": {
      "st": "urn:schemas-upnp-org:device:InternetGatewayDevice:2"
    }
  },
  {
    "brand": "LG webOS TV",
    "match": {
      "st": "urn:lge-com:service:webos-second-screen:1"
    }
  },
  {
    "brand": "Belkin WeMo",
    "match": {
      "manufacturer": "Belkin International Inc."
    }
  },
  {
    "brand": "WiLight",
    "match": {
      "manufacturer": "All Automacao Ltda"
    }
  },
  {
    "brand": "Xbox",
    "match": {
      "manufacturer": "Microsoft Corporation",
      "modelName": "Xbox 360"
    }
  },
  {
    "brand": "Xbox",
    "match": {
      "manufacturer": "Microsoft Corporation",
      "modelName": "Xbox One"
    }
  },
  {
    "brand": "MusicCast",
    "match": {
      "manufacturer": "Yamaha Corporation"
    }
  }
];

// Hostname glob → brand.
export const HA_HOSTNAMES: [pattern: string, brand: string][] = [
  [
    "neo-*",
    "Actron Air"
  ],
  [
    "airobot-thermostat-*",
    "Airobot"
  ],
  [
    "airthings-view",
    "Airthings"
  ],
  [
    "airthings-hub",
    "Airthings"
  ],
  [
    "gdocntl-*",
    "Aladdin Connect"
  ],
  [
    "connect",
    "August"
  ],
  [
    "august*",
    "August"
  ],
  [
    "axis-00408c*",
    "Axis"
  ],
  [
    "axis-accc8e*",
    "Axis"
  ],
  [
    "axis-b8a44f*",
    "Axis"
  ],
  [
    "axis-e82725*",
    "Axis"
  ],
  [
    "rollergate*",
    "BleBox devices"
  ],
  [
    "gatebox*",
    "BleBox devices"
  ],
  [
    "doorbox*",
    "BleBox devices"
  ],
  [
    "shutterbox*",
    "BleBox devices"
  ],
  [
    "switchbox*",
    "BleBox devices"
  ],
  [
    "dimmerbox*",
    "BleBox devices"
  ],
  [
    "dacbox*",
    "BleBox devices"
  ],
  [
    "wlightbox*",
    "BleBox devices"
  ],
  [
    "pixelbox*",
    "BleBox devices"
  ],
  [
    "saunabox*",
    "BleBox devices"
  ],
  [
    "thermobox*",
    "BleBox devices"
  ],
  [
    "tempsensor*",
    "BleBox devices"
  ],
  [
    "energymeter*",
    "BleBox devices"
  ],
  [
    "airsensor*",
    "BleBox devices"
  ],
  [
    "humiditysensor*",
    "BleBox devices"
  ],
  [
    "rainsensor*",
    "BleBox devices"
  ],
  [
    "floodsensor*",
    "BleBox devices"
  ],
  [
    "luxsensor*",
    "BleBox devices"
  ],
  [
    "inputsensor*",
    "BleBox devices"
  ],
  [
    "opensensor*",
    "BleBox devices"
  ],
  [
    "windsensor*",
    "BleBox devices"
  ],
  [
    "co2sensor*",
    "BleBox devices"
  ],
  [
    "simongo*",
    "BleBox devices"
  ],
  [
    "sabaj-k-smrt*",
    "BleBox devices"
  ],
  [
    "rico*",
    "BleBox devices"
  ],
  [
    "smartrollergate*",
    "BleBox devices"
  ],
  [
    "darco_ero_32ws_0*",
    "BleBox devices"
  ],
  [
    "pergoladc*",
    "BleBox devices"
  ],
  [
    "seltsmartscreen*",
    "BleBox devices"
  ],
  [
    "seltvenetianblind*",
    "BleBox devices"
  ],
  [
    "doorunitbox*",
    "BleBox devices"
  ],
  [
    "drutexsmart*",
    "BleBox devices"
  ],
  [
    "swingatecontroller*",
    "BleBox devices"
  ],
  [
    "windowopener*",
    "BleBox devices"
  ],
  [
    "smartawning*",
    "BleBox devices"
  ],
  [
    "smartshade*",
    "BleBox devices"
  ],
  [
    "smartshutter*",
    "BleBox devices"
  ],
  [
    "blink*",
    "Blink"
  ],
  [
    "bond-*",
    "Bond"
  ],
  [
    "dsp-w215",
    "D-Link Wi-Fi Smart Plugs"
  ],
  [
    "duco_[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]",
    "Duco"
  ],
  [
    "emonitor*",
    "SiteSage Emonitor"
  ],
  [
    "flume-gw-*",
    "Flume"
  ],
  [
    "[ba][lk]*",
    "Magic Home"
  ],
  [
    "[hba][flk]*",
    "Magic Home"
  ],
  [
    "lwip*",
    "Magic Home"
  ],
  [
    "hf-lpb100-zj*",
    "Magic Home"
  ],
  [
    "zengge_[0-9a-f][0-9a-f]_*",
    "Magic Home"
  ],
  [
    "zengge",
    "Magic Home"
  ],
  [
    "sta*",
    "Magic Home"
  ],
  [
    "fyta*",
    "FYTA"
  ],
  [
    "yeti*",
    "Goal Zero Yeti"
  ],
  [
    "ismartgate*",
    "Gogogate2 and ismartgate"
  ],
  [
    "gvc*",
    "Elexa Guardian"
  ],
  [
    "guardian*",
    "Elexa Guardian"
  ],
  [
    "kessel*",
    "Guntamatic"
  ],
  [
    "balay-*",
    "Home Connect"
  ],
  [
    "(balay|bosch|neff|siemens)-*",
    "Home Connect"
  ],
  [
    "(bosch|neff|siemens)-*",
    "Home Connect"
  ],
  [
    "hunter*",
    "Hunter Douglas PowerView"
  ],
  [
    "iaqualink-*",
    "Jandy iAquaLink"
  ],
  [
    "rfgateway",
    "Intergas gateway"
  ],
  [
    "zentrios-*",
    "IntelliFire"
  ],
  [
    "isy*",
    "Universal Devices ISY/IoX"
  ],
  [
    "eisy*",
    "Universal Devices ISY/IoX"
  ],
  [
    "polisy*",
    "Universal Devices ISY/IoX"
  ],
  [
    "knc*",
    "Knocki"
  ],
  [
    "gs[0-9][0-9][0-9][0-9][0-9][0-9]",
    "La Marzocco"
  ],
  [
    "lm[0-9][0-9][0-9][0-9][0-9][0-9]",
    "La Marzocco"
  ],
  [
    "mr[0-9][0-9][0-9][0-9][0-9][0-9]",
    "La Marzocco"
  ],
  [
    "litter-robot4",
    "Whisker"
  ],
  [
    "whiskerrobots",
    "Whisker"
  ],
  [
    "lyric-*",
    "Honeywell Lyric"
  ],
  [
    "motion_*",
    "Motionblinds"
  ],
  [
    "brel_*",
    "Motionblinds"
  ],
  [
    "connector_*",
    "Motionblinds"
  ],
  [
    "mystrom-*",
    "myStrom"
  ],
  [
    "xl857-*",
    "Nexia/American Standard/Trane"
  ],
  [
    "hub*",
    "Nobø Ecohub"
  ],
  [
    "nuheat",
    "NuHeat"
  ],
  [
    "nuki_bridge_*",
    "Nuki Bridge"
  ],
  [
    "gateway*",
    "Overkiz"
  ],
  [
    "connbox*",
    "Palazzetti"
  ],
  [
    "ps5-*",
    "PlayStation Network"
  ],
  [
    "ps4-*",
    "PlayStation Network"
  ],
  [
    "ps3",
    "PlayStation Network"
  ],
  [
    "kommspot",
    "SEKO PoolDose"
  ],
  [
    "1118431-*",
    "Tesla Powerwall"
  ],
  [
    "1232100-*",
    "Tesla Powerwall"
  ],
  [
    "teslapw_*",
    "Tesla Powerwall"
  ],
  [
    "rachio-*",
    "Rachio"
  ],
  [
    "thermostat*",
    "Radio Thermostat"
  ],
  [
    "kohlergen*",
    "Rehlko"
  ],
  [
    "reolink*",
    "Reolink"
  ],
  [
    "ring*",
    "Ring"
  ],
  [
    "roborock-*",
    "Roborock"
  ],
  [
    "irobot-*",
    "iRobot Roomba and Braava"
  ],
  [
    "roomba-*",
    "iRobot Roomba and Braava"
  ],
  [
    "ruuvigateway*",
    "Ruuvi Gateway"
  ],
  [
    "tizen*",
    "Samsung Smart TV"
  ],
  [
    "pentair*",
    "Pentair ScreenLogic"
  ],
  [
    "sense-*",
    "Sense"
  ],
  [
    "sensibo*",
    "Sensibo"
  ],
  [
    "simplisafe*",
    "SimpliSafe"
  ],
  [
    "sma*",
    "SMA Solar"
  ],
  [
    "st*",
    "SmartThings"
  ],
  [
    "smartthings*",
    "SmartThings"
  ],
  [
    "smarthub",
    "SmartThings"
  ],
  [
    "samsung-*",
    "SmartThings"
  ],
  [
    "target",
    "SolarEdge"
  ],
  [
    "somfy_*",
    "Somfy MyLink"
  ],
  [
    "squeezebox*",
    "Squeezebox (Lyrion Music Server)"
  ],
  [
    "my[45]50*",
    "Steamist"
  ],
  [
    "servicewelt*",
    "STIEBEL ELTRON"
  ],
  [
    "tado*",
    "Tado"
  ],
  [
    "teslawallconnector_*",
    "Tesla Wall Connector"
  ],
  [
    "usr-tcp232-ed2",
    "TOLO Sauna"
  ],
  [
    "eneco-*",
    "Toon"
  ],
  [
    "e[sp]*",
    "TP-Link Smart Home"
  ],
  [
    "hs*",
    "TP-Link Smart Home"
  ],
  [
    "k[lps]*",
    "TP-Link Smart Home"
  ],
  [
    "p1*",
    "TP-Link Smart Home"
  ],
  [
    "lb*",
    "TP-Link Smart Home"
  ],
  [
    "l[59]*",
    "TP-Link Smart Home"
  ],
  [
    "tp*",
    "TP-Link Smart Home"
  ],
  [
    "s5*",
    "TP-Link Smart Home"
  ],
  [
    "h1*",
    "TP-Link Smart Home"
  ],
  [
    "l9*",
    "TP-Link Smart Home"
  ],
  [
    "p3*",
    "TP-Link Smart Home"
  ],
  [
    "ks2*",
    "TP-Link Smart Home"
  ],
  [
    "kh1*",
    "TP-Link Smart Home"
  ],
  [
    "twinkly_*",
    "Twinkly"
  ],
  [
    "twinkly-*",
    "Twinkly"
  ],
  [
    "velux_klf*",
    "Velux"
  ],
  [
    "levoit-*",
    "VeSync"
  ],
  [
    "sugarwifi",
    "Vistapool"
  ],
  [
    "wiz_*",
    "WiZ"
  ],
  [
    "xbox*",
    "Xbox"
  ],
  [
    "yale-connect-plus",
    "Yale Home"
  ],
  [
    "yeelink-*",
    "Yeelight"
  ],
  [
    "yoto-*",
    "Yoto"
  ]
];

// Every populated field must match the same BLE advertisement.
export const HA_BLUETOOTH: HaBluetoothRule[] = [
  {
    "brand": "Acaia",
    "manufacturerId": 16962
  },
  {
    "brand": "Acaia",
    "localName": "ACAIA*"
  },
  {
    "brand": "Acaia",
    "localName": "PYXIS-*"
  },
  {
    "brand": "Acaia",
    "localName": "LUNAR-*"
  },
  {
    "brand": "Acaia",
    "localName": "PROCHBT001"
  },
  {
    "brand": "Airthings BLE",
    "manufacturerId": 820,
    "serviceUuid": "b42e1f6e-ade7-11e4-89d3-123b93f75cba"
  },
  {
    "brand": "Airthings BLE",
    "manufacturerId": 820,
    "serviceUuid": "b42e4a8e-ade7-11e4-89d3-123b93f75cba"
  },
  {
    "brand": "Airthings BLE",
    "manufacturerId": 820,
    "serviceUuid": "b42e1c08-ade7-11e4-89d3-123b93f75cba"
  },
  {
    "brand": "Airthings BLE",
    "manufacturerId": 820,
    "serviceUuid": "b42e3882-ade7-11e4-89d3-123b93f75cba"
  },
  {
    "brand": "Airthings BLE",
    "manufacturerId": 820,
    "serviceUuid": "b42e90a2-ade7-11e4-89d3-123b93f75cba"
  },
  {
    "brand": "Aranet",
    "manufacturerId": 1794,
    "serviceUuid": "f0cd1400-95da-4f4b-9ac8-aa55d312af0c"
  },
  {
    "brand": "Aranet",
    "manufacturerId": 1794,
    "serviceUuid": "0000fce0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Elgato Avea",
    "localName": "Avea*",
    "serviceUuid": "f815e810-456c-6761-746f-4d756e696368"
  },
  {
    "brand": "BlueMaestro",
    "manufacturerId": 307
  },
  {
    "brand": "BTHome",
    "serviceDataUuid": "0000181c-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "BTHome",
    "serviceDataUuid": "0000181e-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "BTHome",
    "serviceDataUuid": "0000fcd2-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Casper Glow",
    "localName": "Jar*"
  },
  {
    "brand": "Chef iQ",
    "manufacturerId": 1485
  },
  {
    "brand": "Dormakaba dKey",
    "serviceUuid": "e7a60000-6639-429f-94fd-86de8ea26897"
  },
  {
    "brand": "Dormakaba dKey",
    "serviceUuid": "e7a60001-6639-429f-94fd-86de8ea26897"
  },
  {
    "brand": "eQ-3 Bluetooth Smart Thermostats",
    "localName": "CC-RT-BLE"
  },
  {
    "brand": "eQ-3 Bluetooth Smart Thermostats",
    "localName": "CC-RT-M-BLE"
  },
  {
    "brand": "eQ-3 Bluetooth Smart Thermostats",
    "localName": "CC-RT-BLE-EQ"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9120"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9130"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9140"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9146"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9147"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9148"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9149"
  },
  {
    "brand": "EufyLife",
    "localName": "eufy T9150"
  },
  {
    "brand": "Eurotronic Comet Blue",
    "serviceUuid": "47e9ee00-47e9-11e4-8939-164230d1df67"
  },
  {
    "brand": "Fjäråskupan",
    "serviceUuid": "77a2bd49-1e5a-4961-bba1-21f34fa4bc7b"
  },
  {
    "brand": "Gardena Bluetooth",
    "manufacturerId": 1062,
    "serviceUuid": "98bd0001-0b0e-421a-84e5-ddbf75dc6de4"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "Govee*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GVH5*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "B5178*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5121*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5122*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5123*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5124*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5125*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5126*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5179*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GVH5127*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GVH5130*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GVH5110*"
  },
  {
    "brand": "Govee Bluetooth",
    "localName": "GV5140*"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 1,
    "serviceUuid": "0000ec88-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 6966,
    "serviceUuid": "00008451-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 63391,
    "serviceUuid": "00008351-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 26589,
    "serviceUuid": "00008351-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 57391,
    "serviceUuid": "00008351-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 18994,
    "serviceUuid": "00008551-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 818,
    "serviceUuid": "00008551-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 53579,
    "serviceUuid": "00008151-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 43682,
    "serviceUuid": "00008151-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 59970,
    "serviceUuid": "00008151-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 63585,
    "serviceUuid": "00008151-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 14474,
    "serviceUuid": "00008151-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 10032,
    "serviceUuid": "00008251-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 19506,
    "serviceUuid": "00001801-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 61320
  },
  {
    "brand": "Govee Bluetooth",
    "manufacturerId": 34819,
    "manufacturerDataStart": [
      236,
      0,
      0,
      1
    ]
  },
  {
    "brand": "HomeKit Device",
    "manufacturerId": 76,
    "manufacturerDataStart": [
      6
    ]
  },
  {
    "brand": "Philips Hue BLE",
    "serviceUuid": "0000fe0f-0000-1000-8000-00805f9b34fb",
    "serviceDataUuid": "0000fe0f-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Husqvarna Automower BLE",
    "serviceUuid": "98bd0001-0b0e-421a-84e5-ddbf75dc6de4"
  },
  {
    "brand": "iBeacon Tracker",
    "manufacturerId": 76,
    "manufacturerDataStart": [
      2,
      21
    ]
  },
  {
    "brand": "IKEA Idasen Desk",
    "serviceUuid": "99fa0001-338a-1024-8a49-009c0215f78a"
  },
  {
    "brand": "Improv via BLE",
    "serviceUuid": "00467768-6228-2272-4663-277478268000",
    "serviceDataUuid": "00004677-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "INKBIRD",
    "localName": "sps"
  },
  {
    "brand": "INKBIRD",
    "localName": "Inkbird*"
  },
  {
    "brand": "INKBIRD",
    "localName": "iBBQ*"
  },
  {
    "brand": "INKBIRD",
    "localName": "xBBQ*"
  },
  {
    "brand": "INKBIRD",
    "localName": "tps"
  },
  {
    "brand": "INKBIRD",
    "localName": "ITH-11-B"
  },
  {
    "brand": "INKBIRD",
    "localName": "ITH-13-B"
  },
  {
    "brand": "INKBIRD",
    "localName": "ITH-21-B"
  },
  {
    "brand": "INKBIRD",
    "localName": "IBS-P02B"
  },
  {
    "brand": "INKBIRD",
    "localName": "Ink@IAM-T1"
  },
  {
    "brand": "INKBIRD",
    "localName": "Ink@IAM-T2"
  },
  {
    "brand": "INKBIRD",
    "manufacturerId": 12628,
    "manufacturerDataStart": [
      65,
      67,
      45
    ]
  },
  {
    "brand": "INKBIRD",
    "manufacturerId": 12884,
    "manufacturerDataStart": [
      0,
      98,
      0
    ]
  },
  {
    "brand": "IronOS",
    "serviceUuid": "9eae1000-9d0d-48c5-aa55-33e27f9bc533"
  },
  {
    "brand": "Kegtron",
    "manufacturerId": 65535
  },
  {
    "brand": "Keymitt MicroBot Push",
    "serviceUuid": "0000abcd-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Keymitt MicroBot Push",
    "localName": "mib*"
  },
  {
    "brand": "Kuler Sky",
    "serviceUuid": "8d96a001-0002-64c2-0001-9acc4838521c"
  },
  {
    "brand": "La Marzocco",
    "localName": "MICRA_*"
  },
  {
    "brand": "La Marzocco",
    "localName": "MINI_*"
  },
  {
    "brand": "La Marzocco",
    "localName": "GS3_*"
  },
  {
    "brand": "La Marzocco",
    "localName": "GS3AV_*"
  },
  {
    "brand": "LD2410 BLE",
    "localName": "HLK-LD2410B_*"
  },
  {
    "brand": "LD2410 BLE",
    "localName": "HLK-LD2410_*"
  },
  {
    "brand": "LD2410 BLE",
    "manufacturerId": 256,
    "manufacturerDataStart": [
      7,
      1
    ],
    "serviceUuid": "0000af30-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "LED BLE",
    "localName": "LEDnet*"
  },
  {
    "brand": "LED BLE",
    "localName": "BLE-LED*"
  },
  {
    "brand": "LED BLE",
    "localName": "LEDBLE*"
  },
  {
    "brand": "LED BLE",
    "localName": "Triones*"
  },
  {
    "brand": "LED BLE",
    "localName": "LEDBlue*"
  },
  {
    "brand": "LED BLE",
    "localName": "Dream~*"
  },
  {
    "brand": "LED BLE",
    "localName": "QHM-*"
  },
  {
    "brand": "LED BLE",
    "localName": "AP-*"
  },
  {
    "brand": "LED BLE",
    "localName": "LD-0003"
  },
  {
    "brand": "Medcom Bluetooth",
    "serviceUuid": "39b31fec-b63a-4ef7-b163-a7317872007f"
  },
  {
    "brand": "Melnor Bluetooth",
    "manufacturerId": 13,
    "manufacturerDataStart": [
      89
    ]
  },
  {
    "brand": "Moat",
    "localName": "Moat_S*"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      3
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      4
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      5
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      6
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      8
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      9
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      10
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      11
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Mopeka",
    "manufacturerId": 89,
    "manufacturerDataStart": [
      12
    ],
    "serviceUuid": "0000fee5-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Motionblinds Bluetooth",
    "localName": "MOTION_*"
  },
  {
    "brand": "OpenDisplay",
    "manufacturerId": 9286
  },
  {
    "brand": "Oral-B",
    "manufacturerId": 220
  },
  {
    "brand": "Probe Plus",
    "localName": "FM2*",
    "manufacturerId": 36606
  },
  {
    "brand": "Qingping",
    "localName": "Qingping*"
  },
  {
    "brand": "Qingping",
    "localName": "Lee Guitars*"
  },
  {
    "brand": "Qingping",
    "serviceDataUuid": "0000fdcd-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "RAPT Bluetooth",
    "manufacturerId": 16722,
    "manufacturerDataStart": [
      80,
      84
    ]
  },
  {
    "brand": "RAPT Bluetooth",
    "manufacturerId": 17739,
    "manufacturerDataStart": [
      71
    ]
  },
  {
    "brand": "Ruuvi BLE",
    "manufacturerId": 1177
  },
  {
    "brand": "Ruuvi BLE",
    "localName": "Ruuvi *"
  },
  {
    "brand": "Sensirion BLE",
    "manufacturerId": 1749
  },
  {
    "brand": "Sensirion BLE",
    "localName": "MyCO2*"
  },
  {
    "brand": "SensorPro",
    "manufacturerId": 43605,
    "manufacturerDataStart": [
      1,
      1,
      164,
      193
    ]
  },
  {
    "brand": "SensorPro",
    "manufacturerId": 43605,
    "manufacturerDataStart": [
      1,
      5,
      164,
      193
    ]
  },
  {
    "brand": "SensorPush",
    "localName": "SensorPush*"
  },
  {
    "brand": "SensorPush",
    "localName": "s",
    "serviceUuid": "ef090000-11d6-42ba-93b8-9dd7ec090aa9"
  },
  {
    "brand": "Shelly",
    "localName": "Shelly*"
  },
  {
    "brand": "Shelly",
    "manufacturerId": 2985
  },
  {
    "brand": "Snooz",
    "localName": "Snooz*"
  },
  {
    "brand": "Snooz",
    "serviceUuid": "729f0608-496a-47fe-a124-3a62aaa3fbc0"
  },
  {
    "brand": "SwitchBot Bluetooth",
    "serviceDataUuid": "00000d00-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "SwitchBot Bluetooth",
    "serviceDataUuid": "0000fd3d-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "SwitchBot Bluetooth",
    "serviceUuid": "cba20d00-224d-11e6-9fb8-0002a5d5c51b"
  },
  {
    "brand": "SwitchBot Bluetooth",
    "manufacturerId": 2409
  },
  {
    "brand": "SwitchBot Bluetooth",
    "manufacturerId": 89
  },
  {
    "brand": "SwitchBot Bluetooth",
    "manufacturerId": 741
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 16,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 17,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 20,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 21,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 24,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 27,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "manufacturerId": 48,
    "manufacturerDataStart": [
      0
    ],
    "serviceUuid": "0000fff0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "ThermoBeacon",
    "localName": "ThermoBeacon"
  },
  {
    "brand": "ThermoPro",
    "localName": "TP35*"
  },
  {
    "brand": "ThermoPro",
    "localName": "TP39*"
  },
  {
    "brand": "ThermoPro",
    "localName": "TP96*"
  },
  {
    "brand": "ThermoPro",
    "localName": "TP97*"
  },
  {
    "brand": "Tilt Hydrometer BLE",
    "manufacturerId": 76,
    "manufacturerDataStart": [
      2,
      21,
      164,
      149,
      187
    ]
  },
  {
    "brand": "ToGrill",
    "manufacturerId": 34714,
    "serviceUuid": "0000cee0-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Victron BLE",
    "manufacturerId": 737,
    "manufacturerDataStart": [
      16
    ]
  },
  {
    "brand": "Xiaomi BLE",
    "serviceDataUuid": "0000181b-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Xiaomi BLE",
    "serviceDataUuid": "0000181d-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Xiaomi BLE",
    "serviceDataUuid": "0000fd50-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Xiaomi BLE",
    "serviceDataUuid": "0000fe95-0000-1000-8000-00805f9b34fb"
  },
  {
    "brand": "Yale Access Bluetooth",
    "manufacturerId": 465,
    "serviceUuid": "0000fe24-0000-1000-8000-00805f9b34fb"
  }
];
