// Regenerates src/scanner/lan/ouiVendors.generated.ts from the IEEE MA-L OUI
// registry (public domain). We keep only networking-equipment vendors — the
// devices that act as a Wi-Fi access point / router — because the one MAC a
// mobile OS still lets us see is our own gateway's BSSID (see router.ts).
//
//   node scripts/generate-oui.mjs
//
// Commit the regenerated file.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const SOURCE = 'https://standards-oui.ieee.org/oui/oui.csv';
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'scanner',
  'lan',
  'ouiVendors.generated.ts'
);

// Vendors whose OUIs we care about: routers, access points, and gateways a home
// or office network is likely to hand out over Wi-Fi. Matched case-insensitively
// against the IEEE "Organization Name" column.
const NETWORKING_VENDORS =
  /netgear|tp-?link|\basus\b|asustek|d-?link|linksys|belkin|ubiquiti|mikrotik|aruba|\bcisco\b|meraki|zyxel|tenda|\bhuawei\b|\bzte\b|technicolor|\barris\b|commscope|sagemcom|\bavm\b|fritz|ruckus|fortinet|juniper|extreme networks|cambium|actiontec|netis|totolink|\beero\b|amplifi|netcomm|draytek|keenetic|ruijie|\bh3c\b|engenius|grandstream|turris|plume|\bcalix\b|adtran|pakedge|peplink|teltonika|\bnokia\b|\bxiaomi\b|\btenda\b|edimax|buffalo|synology|qnap|openwrt|\bgl\.inet|gl technologies| tenda /i;

// Trim IEEE's long legal names down to a recognisable brand.
function cleanVendor(name) {
  return (
    name
      .replace(/[",]/g, '')
      .replace(
        /\b(inc|incorporated|corp|corporation|co|ltd|limited|llc|gmbh|s\.a\.|s\.r\.l|sa|ag|plc|technologies|technology|electronics|networks|network|systems|international|group|holdings|company|europe|usa|america)\b/gi,
        ''
      )
      .replace(/\s+/g, ' ')
      // Drop stray separators left where a stripped word used to be ("Huawei ." ).
      .replace(/^[\s.,&-]+|[\s.,&-]+$/g, '')
      .trim()
  );
}

const res = await fetch(SOURCE);
if (!res.ok) throw new Error(`Failed to fetch OUI registry: ${res.status}`);
const csv = await res.text();

const vendors = {};
// Columns: Registry,Assignment,Organization Name,Organization Address
for (const line of csv.split('\n')) {
  const match = line.match(/^MA-L,([0-9A-Fa-f]{6}),"?(.*?)"?,/);
  if (!match) continue;
  const [, assignment, rawName] = match;
  if (!NETWORKING_VENDORS.test(rawName)) continue;
  const cleaned = cleanVendor(rawName);
  if (cleaned) vendors[assignment.toUpperCase()] = cleaned;
}

const count = Object.keys(vendors).length;
if (count < 200) {
  throw new Error(`Suspiciously few OUIs (${count}) — source format likely changed.`);
}

const contents = `// AUTO-GENERATED by scripts/generate-oui.mjs — DO NOT EDIT BY HAND.
// Source: IEEE MA-L OUI registry (public domain), filtered to networking
// (router / access-point) vendors. Regenerate with:
// node scripts/generate-oui.mjs

// 24-bit OUI (uppercase hex, no separators) -> vendor brand.
export const OUI_VENDORS: Record<string, string> = ${JSON.stringify(vendors)};
`;

writeFileSync(OUT, contents);
console.log(`Wrote ${OUT}: ${count} networking-vendor OUIs.`);
