// Regenerates the compact TypeScript BLE matcher table from Theengs Decoder's
// GPL-3.0-or-later device definitions. The native Theengs Node/C++ wrapper does
// not run under React Native, so Lantern evaluates the same top-level device
// conditions in TypeScript and leaves measurement decoding to device-specific
// code.
//
//   node scripts/generate-theengs.mjs
//
// Commit the regenerated file.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const BASE = 'https://raw.githubusercontent.com/theengs/decoder/development/src';
const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'scanner',
  'fingerprint',
  'theengs.generated.ts'
);

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Failed to fetch ${url}: ${response.status}`);
  return response.text();
}

const devicesHeader = await fetchText(`${BASE}/devices.h`);
const filenames = Array.from(
  new Set(Array.from(devicesHeader.matchAll(/#include "devices\/(.+?\.h)"/g), (match) => match[1]))
);

const queue = [...filenames];
const sources = [];
await Promise.all(
  Array.from({ length: 16 }, async () => {
    while (queue.length > 0) {
      const filename = queue.pop();
      sources.push([filename, await fetchText(`${BASE}/devices/${filename}`)]);
    }
  })
);

const rules = [];
for (const [filename, source] of sources) {
  // The generated headers contain escaped JSON in one-line C string literals.
  for (const match of source.matchAll(
    /const char\*\s+_[A-Za-z0-9_]+\s*=\s*("(?:\\.|[^"\\])*");/g
  )) {
    try {
      const definition = JSON.parse(JSON.parse(match[1]));
      if (
        typeof definition.brand !== 'string' ||
        typeof definition.model !== 'string' ||
        !Array.isArray(definition.condition)
      ) {
        continue;
      }
      const brand = definition.brand === 'GENERIC' ? '' : definition.brand;
      const label =
        !brand || definition.model.toLowerCase().startsWith(brand.toLowerCase())
          ? definition.model
          : `${brand} ${definition.model}`;
      rules.push({
        label,
        condition: definition.condition,
        ...(Array.isArray(definition.conditionnomac)
          ? { conditionNoMac: definition.conditionnomac }
          : {}),
        source: filename,
      });
    } catch {
      // Property-only strings and non-JSON constants are expected in headers.
    }
  }
}

if (rules.length < 140) {
  throw new Error(`Parsed only ${rules.length} rules — upstream format likely changed.`);
}

rules.sort((a, b) => a.label.localeCompare(b.label) || a.source.localeCompare(b.source));

const contents = `// AUTO-GENERATED by scripts/generate-theengs.mjs — DO NOT EDIT BY HAND.
// Source: theengs/decoder device definitions (GPL-3.0-or-later).
// Lantern's TypeScript condition evaluator is a port adapted for React Native.
// Regenerate with: node scripts/generate-theengs.mjs

export type TheengsConditionToken = string | number | boolean | TheengsConditionToken[];

export type TheengsRule = {
  label: string;
  condition: TheengsConditionToken[];
  conditionNoMac?: TheengsConditionToken[];
  source: string;
};

export const THEENGS_RULES: TheengsRule[] = ${JSON.stringify(rules)};
`;

writeFileSync(OUT, contents);
console.log(`Wrote ${OUT}: ${rules.length} Theengs device rules from ${filenames.length} headers.`);
